#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

SSH_USER=$1
SSH_NAME=$2
DOKKU_COMMAND=$3

if [[ $SSH_USER == dokku && $SSH_NAME == *-deploy ]]
then
  case $DOKKU_COMMAND in
    apps:destroy|events:*|ssh-keys:*)
    echo "Permission Denied: Please contact operation adminis."
    exit 1
    ;;
  esac
fi

exit 0
